config/routes.rb
Rails.application.routes.draw do

  resources :user_projects
  resources :artifacts
  resources :tenants do
    resources :projects do
      get 'users', on: :member 
      put 'add_user', on: :member 
    end
  end
  resources :members
  get 'home/index'

   root :to => "home#index"

    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions", 
    :passwords => "milia/passwords", 
  }
  
  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan


end

app/models/artifact.rb
class Artifact < ActiveRecord::Base
  
  before_save :upload_to_s3
  attr_accessor :upload
  belongs_to :project
  
  MAX_FILESIZE = 10.megabytes
  validates_presence_of :name, :upload
  validates_uniqueness_of :name
  
  validate :uploaded_fize_size
  
  private
  
  def upload_to_s3
    s3 = Aws::S3::Resource.new(
      access_key_id: 'AKIAJQQD4DISEBLJ4B6Q',
      secret_access_key: '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'
    )
    tenant_name = Tenant.find(Thread.current[:tenant_id]).name
    obj = s3.bucket(ENV['S3_BUCKET']).object("#{tenant_name}/#{upload.original_filename}")
    obj.upload_file(upload.path, acl:'public-read')
    self.key = obj.public_url
  end
  
  def uploaded_fize_size
    if upload 
      errors.add(:upload, "File size must be less than #{self.class::MAX_FILESIZE}") unless upload.size <= self.class::MAX_FILESIZE
    end
  end
end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :set_artifact, only: [:show, :edit, :update, :destroy]

  # GET /artifacts
  # GET /artifacts.json
  def index
    @artifacts = Artifact.all
  end

  # GET /artifacts/1
  # GET /artifacts/1.json
  def show
  end

  # GET /artifacts/new
  def new
    @artifact = Artifact.new
    @artifact.project_id = params[:project_id]
  end

  # GET /artifacts/1/edit
  def edit
  end

  # POST /artifacts
  # POST /artifacts.json
  def create
    @artifact = Artifact.new(artifact_params)

    respond_to do |format|
      if @artifact.save
        format.html { redirect_to tenant_project_url(tenant_id: Tenant.current_tenant_id, 
                id: @artifact.project_id), notice: 'Artifact was successfully created.' }
        format.json { render :show, status: :created, location: @artifact }
      else
        format.html { render :new }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artifacts/1
  # PATCH/PUT /artifacts/1.json
  def update
    respond_to do |format|
      if @artifact.update(artifact_params)
        format.html { redirect_to @artifact, notice: 'Artifact was successfully updated.' }
        format.json { render :show, status: :ok, location: @artifact }
      else
        format.html { render :edit }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artifacts/1
  # DELETE /artifacts/1.json
  def destroy
    @artifact.destroy
    respond_to do |format|
      format.html { redirect_to tenant_project_url(tenant_id: Tenant.current_tenant_id, id: @artifact.project_id), notice: 'Artifact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artifact
      @artifact = Artifact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artifact_params
      params.require(:artifact).permit(:name, :project_id, :upload)
    end
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/views/artifacts/_form.html.erb
<%= form_for @artifact, :html => { :class => "form-horizontal artifact" } do |f| %>

    <% if @artifact.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@artifact.errors.count, "error") %> prohibited this artifact from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @artifact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :upload, value: 'File to upload', :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :upload, :class => 'form-control' %>
    </div>
  </div>
  <%= f.hidden_field :project_id %>
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            tenant_project_path(tenant_id: Tenant.current_tenant_id, 
                                id: @artifact.project_id), :class => 'btn btn-default' %>

<% end %>

app/views/artifacts/_list.html.erb
<%- model_class = Artifact -%>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:key) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% artifacts.each do |artifact| %>
      <tr>
        <td><%= link_to artifact.name, artifact_path(artifact), class: 'main-link' %></td>
        <td><%= s3_link Tenant.current_tenant_id, artifact.key %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      artifact_path(artifact),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Artifact', new_artifact_path(project_id: @project.id),
            :class => 'btn btn-primary' %>

app/views/artifacts/edit.html.erb
<%- model_class = Artifact -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/artifacts/index.html.erb
<%= render 'artifacts/list', artifacts: @project.artifacts %>

app/views/artifacts/new.html.erb
<%- model_class = Artifact -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/artifacts/show.html.erb
<%- model_class = Artifact -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @artifact.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:key) %>:</strong></dt>
  <dd><%= @artifact.key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:project_id) %>:</strong></dt>
  <dd><%= @artifact.project_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              artifacts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_artifact_path(@artifact), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              artifact_path(@artifact),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>